enum VARIABLES {
    PRIMARY_COLOR = "#9EA3F4",
    PRIMARY_COLOR_DARK = "#9B94F3",
    PRIMARY_COLOR_LIGHT = "#B8BCFF",
    SECONDARY_COLOR = "#85C9C9",
    SECONDARY_COLOR_LIGHT = "#9EDCDC",
    GRAY_COLOR = "#A6A6A6",
    GRAY_COLOR_LIGHT = "#E1E1E1",
    WHITE_COLOR = "#EDEFF6",
    PINK_COLOR = "#B990F8"
}

export default VARIABLES;