enum VARIABLES {
    PRIMARY_COLOR = "#9C94F3",
    PRIMARY_COLOR_DARK = "#7269D6",
    PRIMARY_COLOR_LIGHT = "#B8BCFF",
    SECONDARY_COLOR = "#85C9C9",
    SECONDARY_COLOR_DARK = "#4EAAA5",
    SECONDARY_COLOR_LIGHT = "#9EDCDC",
    GRAY_COLOR = "#A6A6A6",
    GRAY_COLOR_LIGHT = "#E1E1E1",
    GRAY_COLOR_DARK = "#373A40",
    WHITE_COLOR = "#EDEFF6",
    PINK_COLOR = "#B990F8",
    RED_COLOR = "#ff758f",
    BLACK_COLOR = "#191919",
    WARNING = "#FFAF45"
}

export default VARIABLES;